### ISSUE TITLE
Fix Search

### ISSUE THREAD

**Issue by starcraftman** [starcraftman/wok#36]
Search is too simple, might add subcommand parsing for it.

Would like to support:
- searching names or description (later maybe tags?)
- toggle case sensitive
- switch between subsequence matching & substring

Mainly a parsing issue, most logic implemented.

**Comment by starcraftman** [comment]
Considering how most of pakit can be configured via the YAML. Should probably have a section in the yaml for configuring default:

``` yaml
search:
  descriptions: true/false
  case-sensitive: true/false
  match-method: subsequence/substring
```

Command could then be:
`pakit search --descriptions`

`pakit search --case`
`pakit search --nocase`

`pakit search --substr`
`pakit search --subseq`

`pakit search term1 term2 term3` Results from searching each term are ORed together into a set.
